require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # In the development environment your application's code is reloaded any time
  # it changes. This slows down response time but is perfect for development
  # since you don't have to restart the web server when you make code changes.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable caching. By default caching is disabled.
  # Run rails dev:cache to toggle caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.cache_store = :memory_store
    config.public_file_server.headers = { "Cache-Control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false

    config.cache_store = :null_store
  end

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # ADR-0011: check-in photos / message media (ActiveStorage) generate
  # absolute blob URLs (`rails_blob_url`) for the caregiver/cockpit apps to
  # fetch directly (img/video src) — needs an explicit host+port, since the
  # container listens on 3000 but is only reachable from the host browser
  # via the docker-compose port mapping to 3001 (ops/docker-compose.yml).
  Rails.application.routes.default_url_options[:host] = ENV.fetch("APP_HOST", "localhost")
  Rails.application.routes.default_url_options[:port] = ENV.fetch("APP_PORT", 3001)

  # ActionDispatch::HostAuthorization's dev-mode default allowlist covers
  # localhost/127.0.0.1/IP addresses but not the docker-compose service
  # alias ("backend") other containers on the compose network use to reach
  # this one — e.g. ops/k6/load_checkins.js (M7 load gate, ADR-0009 #9)
  # posting against `http://backend:3000` from its own container. Silently
  # 403s ("Blocked hosts") without this. Scoped to development only.
  config.hosts << "backend"

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Disable caching for Action Mailer templates even if Action Controller
  # caching is enabled.
  config.action_mailer.perform_caching = false

  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
    address: ENV.fetch("SMTP_HOST", "localhost"),
    port: ENV.fetch("SMTP_PORT", 1025).to_i
  }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise exceptions for disallowed deprecations.
  config.active_support.disallowed_deprecation = :raise

  # Tell Active Support which deprecation messages to disallow.
  config.active_support.disallowed_deprecation_warnings = []

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # The caregiver/cockpit dev servers (localhost:4200/4300) are a different
  # origin than the API (localhost:3001) — same reason CORS needed
  # configuring (config/initializers/cors.rb).
  config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
